# This is a basic workflow that only runs on schedule

name: vwWorstCovidUpdate

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scheduled:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # retrieve secrets from github
    env:
        RENV_PATHS_ROOT: ~/.local/share/renv
    #
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2
        # with:
        #   token: ${{ secrets.PAT }}

      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.3'
      # install renv package
      - run: R -e 'install.packages("renv")'
      # set up cache
      - name: Cache packages
        uses: actions/cache@v2
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-
      # - run: sudo apt install -y --no-install-recommends libcurl4-openssl-dev
      # - run: sudo apt install libmagick++-dev
      # install c++ dependencies and install necessary packages
      - run: R -e 'renv::restore()'
      - run: Rscript covid19VaxUninsurance.R
        env: 
          DW_API_KEY: ${{ secrets.DW_API_KEY }}
      # execute Rscript
      - run: |-
          git pull
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest Verywell Covid update: ${timestamp}" || exit 0
          git push